name: Main Branch CI

on:
  pull_request:
    branches:
      - main

jobs:
  main-branch-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run prettier formatter
        run: npm run format:check

      - name: Run lint test
        run: npm run lint

      - name: Docker Build Test
        run: docker build -t book-store-api:test .
